#!/bin/bash
# The path to ORCA should be added to .bashrc or exported in command line


if [ -z $2 ]
then
  echo " need two arguments! "
  exit
fi

#echo " in ograd: $1 $2 "

ofile=scratch/orcain$1.in
ofileout=scratch/orcain$1.out
molfile=scratch/structure$1
ncpu=$2

#echo " ofile: $ofile ofileout: $ofileout molfile: $molfile ncpu: $ncpu"

########## DFT settings: #################
#echo '! DFT BP86 ECP{LANL2} ENGRAD' > $ofile
echo '! DFT B3LYP ENGRAD' > $ofile
#echo '! veryslowconv SCFCONV6' >> $ofile
echo '! nomoprint' >> $ofile
echo '%scf' >> $ofile
echo '  maxiter 350' >> $ofile
echo 'end' >> $ofile
# charge and spin multiplicity
echo '* xyz 0 1' >> $ofile
cat $molfile >> $ofile
echo '*' >> $ofile

#echo "running: orca $ofile > $ofileout"
orca $ofile > $ofileout
