##!/bin/bash
##This file was created on 12/12/2016

#this is a pbs script for Athena HPC, change accordingly
PBS -l nodes=1:ppn=4 -l walltime=18:00:00
PBS -N test
PBS -o test.o
PBS -e test.e

cd $PBS_O_WORKDIR
module load CMake
#module load Intel/13.x
pwd
echo $MKLROOT
echo $LD_LIBRARY_PATH
export OMP_NUM_THREADS=1
#source /export/zimmerman/paulzim/qchem/qchemapr272016/paul.set.local
source /export/zimmerman/craldaz/bin/qchem.source
echo "working on ctest"
ctest -V

