#!/bin/bash

list=`ls *.out`
for item in $list
do
  energyLine=`grep 'Final energy is' $item`
  counter=0
  for word in $energyLine
  do
    let counter=counter+1
    energy=$word
  done
  if [ $counter -eq 4 ];
  then
    echo $energy $item >> optimized_energies_output_fromqchem.txt
  else
    echo "Energy N/A       " $item >> optimized_energies_output_fromqchem.txt
  fi 
done

