#!/bin/bash
qJobAry=`ls *.inp.out`
mkdir xyzFiles

for item in $qJobAry
do
  lineEnd=`grep -n "END OF MOLDEN-FORMATTED" $item | grep -Eo '^[^:]+'`
  if [ -z "$lineEnd" ];
  then
    continue
  fi

  lineEndm1=$(($lineEnd-1))

  IFS='.' read -ra nameAry <<< "$item"
  counter=0

  for element in "${nameAry[@]}"
  do
    let counter=counter+1
  done

  counter2=0
  outFileName=
  for element in "${nameAry[@]}"
  do
    if [[ $counter2 -eq 0 || $counter2 -eq $(($counter-2)) ]];
    then
      let counter2=counter2+1
      continue
    fi
  outFileName+=$element
  outFileName+="."
  let counter2=counter2+1 
  done
  outFileName+="xyz"

  alist=`grep -A 1 "NAtoms" $item`
  
  x=0
  for thing in $alist
  do
    if [ $x -eq 8 ]
    then
      echo $thing
      numAtoms=$thing
    fi
    let x=x+1
  done
  
  let lineStart=lineEndm1-numAtoms-3

  lineStart=$(($lineEnd-$numAtoms-3))
  csplit $item $lineStart $lineEndm1
  mv xx01 "xyzFiles/$outFileName"
done

rm xx*
