#!/bin/bash

EXTRA_ARGS=$@

#
# Configure script for a SERIAL RELEASE build with GCC compilers of the
# TriBITS project & package.
#
# This script will work in any platform where the gcc compilers are found by
# default.
#
# This script must be symbolically linked in for it to find the path back to
# the local TriBITS repo.  However, on Mac OSX, one must manually set
# TRIBITS_BASE_DIR in the env before calling this script.
#

if [ "$TRIBITS_BASE_DIR" == "" ] ; then
  _ABS_FILE_PATH=`readlink -f $0` || \
    echo "ERROR: Must set TRIBITS_BASE_DIR in env to TriBITS base dir!"
  _SCRIPT_DIR=`dirname $_ABS_FILE_PATH`
  TRIBITS_BASE_DIR=$_SCRIPT_DIR/../..
fi

cmake \
-D CMAKE_BUILD_TYPE=RELEASE \
-D TPL_ENABLE_MPI=OFF \
-D CMAKE_C_COMPILER=gcc \
-D TriBITS_ENABLE_Fortran=ON \
-D TriBITS_ENABLE_TESTS=ON \
$EXTRA_ARGS \
${TRIBITS_BASE_DIR}

# NOTE: Above we must set CMAKE_C_COMPILER=gcc or CMake will find cc by
# default and then it will not find Fortran.
